# Generated by Django 4.2.25 on 2025-10-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEMAND', '수요'), ('SUPPLY', '공급')], max_length=6)),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
                ('price_type', models.CharField(choices=[('무료', '무료'), ('유료', '유료')], max_length=2)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('conditions', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage', models.CharField(blank=True, choices=[('퇴비', '퇴비용'), ('공예', '공예용')], max_length=2, null=True)),
                ('dry', models.BooleanField(blank=True, null=True)),
                ('package', models.CharField(blank=True, choices=[('있음', '포장 있음'), ('없음', '포장 없음')], max_length=2, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
