# Generated by Django 4.2.25 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usage',
            field=models.CharField(blank=True, choices=[('퇴비', '퇴비용'), ('공예', '공예용'), ('원예', '원예용'), ('연구/실험', '연구/실험'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
