# Generated by Django 4.2.25 on 2025-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='demand_price_pref',
            field=models.CharField(blank=True, choices=[('무료', '무료'), ('유료', '유료')], help_text='무료/유료 중 선택', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_budget',
            field=models.PositiveIntegerField(blank=True, help_text='유료를 선택한 경우 최대 예산(원)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='within_5km',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['lat', 'lng'], name='posts_post_lat_3f127c_idx'),
        ),
    ]
