# Generated by Django 4.2.25 on 2025-11-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='guides/thumbs/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guides.guide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
