# Generated by Django 4.2.25 on 2025-11-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_read_buyer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_read_seller',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
