# Generated by Django 4.2.25 on 2025-11-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_address_post_demand_price_pref_post_max_budget_and_more'),
        ('cart', '0002_alter_cartitem_options_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='posts.post'),
        ),
    ]
